FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
   build-essential \
   cmake \
   g++ \
   make \
   expect \
   lsblk \
   sudo \
   dpkg-dev \
   && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/kubsh

CMD ["make", "test"]